esphome:
  name: refoss-p11-dzuris-home
esp8266:
  board: esp01_1m
logger:
  baud_rate: 0
wifi:
  ssid: #SSID or !secret wifi_ssid
  password: #Password or !secret wifi_password
  manual_ip: #If you don't want set manual IPs, Delete (manual_ip and below that)
    static_ip: #Refoss P11 Device IP
    gateway: #Router IP
    subnet: #Router Subnet IP
  ap:
    ssid: "Refoss P11 Dzuriš Home AP"
    password: #Acess Point password or !secret ap_password
captive_portal:
ota:
  - platform: esphome
    password: #Password or !secret ota_password
